### PREREQUISITES

#### Importing Modules and Tables

In [1]:
import pandas as pd
import re
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

In [65]:
#candidate_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\27395_candidates_for_reprocessing.csv")
vacancy_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\13_posts_vacancy.csv")

In [3]:
candidate_df[candidate_df['exs_reservation'] == 'Yes'].shape[0]

55

In [4]:
candidate_df = candidate_df[candidate_df['total'].notnull()]

In [5]:
candidate_df = candidate_df[candidate_df['age_limit'].notnull()]
candidate_df.shape[0]

27395

In [6]:
post_age_df = pd.read_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\post_age.csv")
post_age_df['dob_from'] = pd.to_datetime(post_age_df['dob_from'])
post_age_df['dob_upto'] = pd.to_datetime(post_age_df['dob_upto'])

In [7]:
post_age_df

    post_code    age                 eq_level   dob_from   dob_upto
0     WR10725  18-25     Matriculation (10th) 2000-08-01 2007-08-02
1     KK10225  18-27  Higher Secondary (10+2) 1998-08-01 2007-08-02
2     NR14325  18-30       Graduation & Above 1995-08-01 2007-08-02
3     WR14125  18-27     Matriculation (10th) 1998-08-01 2007-08-02
4     WR11125  18-27     Matriculation (10th) 1998-08-01 2007-08-02
..        ...    ...                      ...        ...        ...
352   WR14725  18-27       Graduation & Above 1998-08-01 2007-08-02
353   WR10125  18-30  Higher Secondary (10+2) 1995-08-01 2007-08-02
354   ER12925  18-25     Matriculation (10th) 2000-08-01 2007-08-02
355   CR11725  18-25     Matriculation (10th) 2000-08-01 2007-08-02
356   NW11025  18-27     Matriculation (10th) 1998-08-01 2007-08-02

[357 rows x 5 columns]

In [8]:
candidate_df['dob'] = pd.to_datetime(candidate_df['dob'])

In [9]:
group_c_posts = ['ER14425','WR15025','WR15125','ER14025','NR16825','ER12925','NR17425','ER11125','NR16625','CR10525','SR11325','NR17725','SR11125','SR11425','NR20225','NR14625','SR13425','SR11625','NR11325','ER16025','SR10825','WR11925','CR10925','ER11225','WR13625','SR12825','WR12325','WR11825','NR20325','NR14925','ER13025','SR14025','ER15525','ER12625','NR17625','SR10625','WR12025','CR11625','CR10225','WR11025','SR12125','NR17825','ER13625','NR11225','WR11125','SR13125','ER15025','SR11525','ER10225','ER14225','ER14725','SR12925','SR10725','ER10625','ER12325','SR13025','ER12725','NR16925','ER16225','ER15725','CR10125','MP10525','NW11425','KK10525','NW10225','NW10725','NE11125','NE10625','KK12225','NE11925','NW11725','MP11425','CR11725','NE12125','NR20825','NE11425','WR11525','WR12125','CR11025','CR11325','ER15125','MP11125','NW12225','SR13325','WR13925','WR11625','SR13225','ER11925','NR20025','ER13525','ER15225','ER11525','NR15225','ER14825','NR11425','ER17225','WR13525','WR14125','ER10325','NR19725','SR13825','NR17525','ER14925','SR12325','ER11825','ER12425','ER12225','NR18025','WR12625','WR13725','ER10825','WR12525','ER13725','WR10925','WR12225','WR11225','ER15325','SR11225','ER12025','WR10225','SR11725','ER16125','ER14325','NR15125','ER15925','NW10425','SR13725','ER13125','NR11725','NR11625','ER15825','NR11125','NW10925','NR17225','ER15625','ER12125','NR18625','WR12725','WR10825','WR11425','SR11925','ER10125','ER12825','CR10725','ER14125','KK11325','KK11925','NE12025','NW11625','NE10125','MP10125','NE10325','NW10325','NW10525','NW11325','KK11125','NE10925','MP11725','NW11025','NW11225','KK11525','NW12625','MP10625','KK12125','NE10225','NE11725','NE10825','MP10425','KK12425','KK10925','MP11525','KK12025','NE11025','NE10425','KK10625','NW12025','CR11825','CR12025','MP11925','KK12325','NR14725','NW11125','CR11425','CR11225','KK13025','KK13225','KK10825','CR13125','CR13225','MP12425','NW12425','NR16025','WR14425','NR16125','WR14925','KK10225','WR11725','WR14225','WR14525','WR14725','NR18725','WR14625','WR14825','WR10725','MP12225','MP12325','CR13525']

In [10]:
group_b_posts = ('ER12525','NR19925','WR13225','WR13425','NR10125','SR10325','NR18925','ER11025','NR15825','NR14225','ER10925','ER17025','WR10425','NR14325','ER16325','ER11625','NR12225','NR20125','NR15725','NR15625','WR13325','ER13325','NR16425','ER15425','SR10925','SR13925','CR10625','ER13425','ER14625','SR12225','NR15025','NR14825','MP11625','KK11225','NE11325','KK11725','NR21025','NR21225','CR10325','MP13025','CR13325','MP12525','NW12325','NW12525','SR12525','CR10825','SR13525','NR16325','WR10325','ER10425','SR12625','CR10425','WR11325','ER17125','WR10625','NR17025','NR19825','NR16725','ER14525','WR13025','NR18825','NR12025','ER16925','SR10425','WR12425','ER11725','SR10525','CR11125','NR11525','ER10525','SR11025','ER17325','ER13825','NR11825','ER11325','SR10225','WR10525','NR16525','WR10125','NR14425','SR12425','SR12725','SR13625','ER13925','WR12825','WR14325','WR12925','NR20425','ER11425','NR17125','NR17925','NR11925','WR13125','NR12125','NR14525','NR15925','CR11525','ER13225','WR14025','KK11025','KK10725','NW10625','KK11825','NE11225','NW11925','NE11625','MP13225','KK10425','KK12525','KK10125','MP10225','NW10125','KK11625','MP10825','MP10725','NW11525','MP11025','NE11825','NE11525','MP11225','KK10325','NR20725','NR21325','NW12125','MP12025','KK12825','KK12925','KK12625','KK13125','KK12725','MP11825','CR12125','MP13125','CR12225','CR12325','CR12425','CR12525','CR12625','CR12725','CR12925','CR13025','CR13425','MP12725','MP12825','MP12925','KK11425','MP12125','CR12825','MP12625','NW12725','NW12925','CR11925','NW12825','SR12025','WR13825')

In [ ]:
# debarred_regno = (10007996203, 10000940035, 10001171482, 10001351350, 10000169590, 10006132127, 10005684790, 10008590451, 10006487778, 10008558625, 10008298381, 10005954377, 10005869219, 10000927895, 10002164310, 10006691027, 10000988736, 10006723254, 10006417778, 10006231587, 10006719808, 10000949934, 10000800797, 10000070482, 10008131599, 10008303330, 10008602801, 10001791619, 10001079685, 10006617610, 10002097852, 10008076008, 10006663144, 10005901984, 10001222189, 10005765470, 10005895103, 10000706634, 10001810993, 10005498830, 10006599047, 10008083687, 10006812435, 10005870001, 10006639306, 10006135176, 10005912447, 10005946525, 10005769932, 10006508841, 10008127652, 10006583950, 10002101836, 10005685735, 10008227219, 10000146881, 10000996109, 10001117260, 10001260727, 10005719803, 10001799662, 10005678119, 10008108895, 10008501134, 10005799805, 10001089748, 10001755803, 10006676690, 10005471263, 10005912391, 10000816746, 10001825803, 10006607734, 10005630469, 10005661434, 10001291586, 10001831812, 10006700073, 10001714536, 10005788504, 10000150934, 10006693412, 10001224489, 10008305616, 10001066235, 10002141803, 10005942698, 10002172891, 10002169889, 10008128435, 10000797328, 10000006067, 10006894635, 10001646317, 10006134343, 10006576410, 10008513081, 10006564305, 10000031710, 10006438549, 10001062271, 10000982672, 10000901665, 10000997691, 10008486936, 10008233192, 10000917186, 10008126996, 10008298753, 10008398511, 10000068205, 10008332160, 10006731414, 10008080744, 10002076276, 10006780631, 10006640459, 10000780026, 10000855124, 10008130476, 10005857523, 10000158576, 10008038959, 10000109837, 10005806613, 10006529701, 10005725590, 10006730939, 10005471400, 10005750635, 10001203224, 10001585125, 10008552321, 10008484787, 10001721300, 10000698503, 10006114009, 10006787176, 10008582253, 10001219228, 10008212527, 10008307778, 10008530986, 10001595440, 10001154385, 10006544104, 10008079887, 10007531071, 10001804507, 10005797204, 10005784646, 10005755783, 10008303088, 10006689791, 10000011602, 10000101521, 10006641119, 10001053004, 10008159045, 10008635672, 10000853635, 10008347637, 10008289856, 10001339319, 10005699982, 10008063358, 10005641797, 10001105926, 10006523242, 10000843291, 10008585122, 10000089191, 10008553655, 10005603323, 10000698988, 10005862223, 10005926960, 10000191803, 10006891221, 10005706128, 10000043687, 10005806526, 10001515611, 10008220805, 10008001064, 10006458284, 10001281190, 10000756949, 10005691963, 10008030905, 10008088377, 10000716079, 10005918358, 10002057131, 10005804897, 10006625189, 10005928663, 10001655712, 10000732805, 10001641977, 10000919937, 10006476689, 10006588187, 10008036297, 10001755038, 10008461618, 10000951264, 10000773078, 10006722870, 10005792738, 10006608321, 10001724336, 10006657230, 10005866139, 10008072665, 10000702186, 10001324536, 10001177589, 10008008673, 10005847957, 10008011737, 10008245192, 10006231156, 10006570251, 10005837003, 10001029917, 10008458568, 10006723787, 10006157707, 10008090302, 10006810122, 10001807280, 10005957695, 10006582957, 10006556631, 10008643428, 10005695876, 10000049930, 10005682985, 10008152703, 10000723892, 10008488217, 10005936106, 10001821189, 10000737508, 10000850407, 10006505975, 10008300081, 10006550008, 10008054841, 10005466492, 10000704328, 10005697707, 10006506217, 10006255849, 10001496287, 10008384060, 10006573949, 10000020805, 10000893881, 10006328219, 10006363692, 10000760590, 10001035316, 10006585366, 10000875689, 10005926981, 10006108501, 10008180264, 10008627935, 10005922428, 10001114541, 10005858034, 10008602372, 10005784135, 10006487781, 10006470159, 10001470873, 10008088678, 10005756388, 10005770807, 10001115524, 10001774572, 10008455357, 10000090180, 10008416325, 10000842196, 10000056358, 10008447708, 10006609429, 10006536503, 10005714946, 10006509689, 10006461618, 10005897049, 10005958495, 10006655560, 10006794798, 10008386140, 10000000285, 10001280255, 10000054444, 10002052868, 10005803068, 10005845858, 10002079904, 10005740966, 10006485640, 10001617756, 10001766792, 10006594739, 10001243363, 10008187102, 10005904451, 10005928835, 10008588176, 10001112867, 10008070678, 10008324744, 10001218591, 10006499810, 10008585784, 10005731657, 10001295872, 10000859940, 10001818380, 10006667413, 10006583585, 10002108876, 10005891894, 10002108529, 10000169123, 10000925419, 10008572118, 10005847074, 10000113282, 10005694354, 10000995799, 10001292299, 10001660340, 10001618028, 10006785892, 10005703039, 10005781967, 10008112475, 10001124458, 10005755620, 10001607636, 10008400545, 10001114622, 10006711636, 10001221481, 10002127559, 10001168589, 10005635089, 10002045644, 10000037220, 10000090996, 10008452990, 10000141117, 10008453010, 10006793175, 10001201245, 10005692646, 10008486607, 10005640783, 10008134843, 10000125334, 10008556479, 10000055666, 10005727766, 10000707135, 10005812749, 10002067291, 10007998836, 10006101718, 10006608852, 10001208123, 10001044638, 10006658409, 10007986564, 10006536986, 10000999301, 10005920043, 10006653828, 10000057299, 10001115375, 10008231806, 10008495399, 10001226562, 10005899431, 10001361959, 10001791240, 10005917612, 10005494939, 10001136396, 10001356159, 10001456478, 10001064116, 10005667599, 10008551116, 10008515064, 10001321468, 10000671913, 10001187872, 10008554000, 10006705039, 10006486304, 10001623006, 10000084240, 10001820506, 10001626861, 10006729527, 10005684878, 10002099791, 10000668289, 10005866502, 10001134410, 10006514345, 10006565887, 10001786243, 10001344244, 10000958293, 10006651536, 10006735697, 10001612045, 10008409146, 10006467805, 10006486032, 10008510750, 10008576002, 10005778827, 10005956105, 10006125595, 10007530584, 10001787729, 10001208090, 10000027477, 10000013066, 10006416339, 10007998572, 10008130851, 10005694175, 10008586592, 10000854008, 10005741281, 10000847965, 10008598640, 10008294098, 10005843231, 10005785149, 10008485922, 10005638653, 10006277235, 10001347835, 10005861209, 10008518261, 10001349905, 10007521189, 10006532813, 10008631833, 10006589477, 10007517680, 10006782762, 10001131333, 10000922467, 10001735606, 10000073197, 10005730680, 10005913279, 10005675717, 10002102400, 10000923971, 10005851844, 10001679510, 10008481572, 10006505917, 10005662088, 10001151188, 10008191549, 10000858960, 10000033816, 10008123699, 10005754435, 10000875367, 10006656649, 10008023188, 10006647616, 10006104967, 10008445148, 10002113879, 10001766034, 10001359775, 10005920856, 10001350704, 10006699995, 10008119797, 10006585204, 10000905494, 10006438565, 10001051667, 10000171942, 10008475964, 10000828123, 10006472004, 10006588588, 10001800233, 10008293441, 10001019880, 10006682774, 10001662471, 10008379835, 10000747709, 10002176690, 10006617586, 10001771377, 10006829494, 10002055259, 10000820549, 10006657374, 10001166393, 10005753754, 10006562265, 10006599511, 10002151637, 10001106252, 10002109917, 10006693248, 10001312600, 10000997771, 10005825349, 10001276908, 10008088667, 10005692434, 10008326846, 10001676545, 10006616632, 10001161203, 10006550729, 10006274139, 10000049459, 10005923280, 10006728627, 10002058625, 10000841474, 10008071569, 10006641223, 10008186702, 10001766894, 10001211359, 10008579341, 10008010706, 10001230010, 10002090088, 10005656888, 10005782066, 10000789530, 10005802630, 10006290823, 10001203590, 10008554910, 10006544312, 10001064319, 10006561659, 10006682944, 10001592724, 10006539797, 10008489064, 10005926276, 10006680511, 10002035514, 10005842316, 10005765713, 10002092260, 10006709578, 10006651810, 10000731130, 10000963787, 10006695258, 10008310243, 10000957071, 10008170304, 10001313129, 10000996555, 10006529895, 10006519102, 10006535309, 10006265438, 10000929595, 10000100371, 10001025227, 10008377773, 10001835955, 10008180539, 10001786906, 10001294834, 10005877733, 10008577442, 10000929647, 10000824508, 10000105977, 10006734398, 10008642070, 10000832385, 10006245161, 10005742022, 10000775441, 10005960113, 10001198635, 10008589096, 10008183173, 10008163620)

In [ ]:
len(debarred_regno)

#### ARC Table from Notice

In [11]:
arc_dict = [
    {"arc_code": 1, "arc_year": 5, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": None},
    {"arc_code": 2, "arc_year": 3, "arc_cat1": "6", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": None},
    {"arc_code": 3, "arc_year": 10, "arc_cat1": "9,0", "arc_cat2": None, "arc_cat3": "4,5,7,8", "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 23-28, 21-30, 25-30", "arc_year_against_ur": 10},
    {"arc_code": 4, "arc_year": 13, "arc_cat1": "6", "arc_cat2": None, "arc_cat3": "4,5,7,8", "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": 10},
    {"arc_code": 5, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": "4,5,7,8", "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 23-28, 21-30, 25-30", "arc_year_against_ur": 10},
    {"arc_code": 6, "arc_year": 3, "arc_cat1": "1,2,6,9,0", "arc_cat2": "3", "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": None},
    {"arc_code": 8, "arc_year": 3, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": 3},
    {"arc_code": 9, "arc_year": 8, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25, 18-27, 18-28, 18-30, 18-35, 18-37, 18-42, 20-25, 21-25, 21-27, 21-28, 21-30, 23-28, 25-30", "arc_year_against_ur": 3},
    {"arc_code": 10, "arc_year": 15, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25", "arc_year_against_ur": 15},
    {"arc_code": 10, "arc_year": 13, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-27", "arc_year_against_ur": 13},
    #{"arc_code": 10, "arc_year": 12, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-28", "arc_year_against_ur": 12},
    {"arc_code": 10, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-30", "arc_year_against_ur": 10},
    #{"arc_code": 10, "arc_year": 5, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-35", "arc_year_against_ur": 5},
    {"arc_code": 10, "arc_year": 15, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "20-25", "arc_year_against_ur": 15},
    {"arc_code": 10, "arc_year": 15, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-25", "arc_year_against_ur": 15},
    #{"arc_code": 10, "arc_year": 13, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-27", "arc_year_against_ur": 13},
    {"arc_code": 10, "arc_year": 12, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-28", "arc_year_against_ur": 12},
    #{"arc_code": 10, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-30", "arc_year_against_ur": 10},
    #{"arc_code": 10, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "25-30", "arc_year_against_ur": 10},
    {"arc_code": 11, "arc_year": 20, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-25", "arc_year_against_ur": 15},
    {"arc_code": 11, "arc_year": 18, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-27", "arc_year_against_ur": 13},
   # {"arc_code": 11, "arc_year": 17, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-28", "arc_year_against_ur": 12},
    {"arc_code": 11, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-30", "arc_year_against_ur": 10},
    #{"arc_code": 11, "arc_year": 10, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "18-35", "arc_year_against_ur": 5},
    {"arc_code": 11, "arc_year": 20, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "20-25", "arc_year_against_ur": 15},
    {"arc_code": 11, "arc_year": 20, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-25", "arc_year_against_ur": 15},
    #{"arc_code": 11, "arc_year": 18, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-27", "arc_year_against_ur": 13},
    {"arc_code": 11, "arc_year": 17, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-28", "arc_year_against_ur": 12},
    #{"arc_code": 11, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "21-30", "arc_year_against_ur": 10},
    #{"arc_code": 11, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1,2,3", "age_group": "25-30", "arc_year_against_ur": 10},
    {"arc_code": 12, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-25", "arc_year_against_ur": 10},
    {"arc_code": 12, "arc_year": 8, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-27", "arc_year_against_ur": 8},
    #{"arc_code": 12, "arc_year": 7, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-28", "arc_year_against_ur": 7},
    {"arc_code": 12, "arc_year": 5, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-30", "arc_year_against_ur": 5},
    #{"arc_code": 12, "arc_year": 0, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-35", "arc_year_against_ur": 0},
    {"arc_code": 12, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "20-25", "arc_year_against_ur": 10},
    {"arc_code": 12, "arc_year": 10, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-25", "arc_year_against_ur": 10},
    #{"arc_code": 12, "arc_year": 8, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-27", "arc_year_against_ur": 8},
    {"arc_code": 12, "arc_year": 7, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-28", "arc_year_against_ur": 7},
    #{"arc_code": 12, "arc_year": 5, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-30", "arc_year_against_ur": 5},
    #{"arc_code": 12, "arc_year": 5, "arc_cat1": "6,9,0", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "25-30", "arc_year_against_ur": 5},
    {"arc_code": 13, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-25", "arc_year_against_ur": 10},
    {"arc_code": 13, "arc_year": 13, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-27", "arc_year_against_ur": 8},
    #{"arc_code": 13, "arc_year": 12, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-28", "arc_year_against_ur": 7},
    {"arc_code": 13, "arc_year": 10, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-30", "arc_year_against_ur": 5},
    #{"arc_code": 13, "arc_year": 5, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "18-35", "arc_year_against_ur": 0},
    {"arc_code": 13, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "20-25", "arc_year_against_ur": 10},
    {"arc_code": 13, "arc_year": 15, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-25", "arc_year_against_ur": 10},
    #{"arc_code": 13, "arc_year": 13, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-27", "arc_year_against_ur": 8},
    {"arc_code": 13, "arc_year": 12, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-28", "arc_year_against_ur": 7}
    #{"arc_code": 13, "arc_year": 10, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "21-30", "arc_year_against_ur": 5},
    #{"arc_code": 13, "arc_year": 10, "arc_cat1": "1,2", "arc_cat2": None, "arc_cat3": None, "arc_gender": "1", "age_group": "25-30", "arc_year_against_ur": 5}
]


arc_df = pd.DataFrame(arc_dict)

#### Cutoff Table from Notice

In [12]:
cutoff_data = [
    {"serial_id": 1, "category": 1, "total": 40},
    {"serial_id": 2, "category": 2, "total": 40},
    {"serial_id": 3, "category": 6, "total": 50},
    {"serial_id": 4, "category": 9, "total": 60},
    {"serial_id": 5, "category": 0, "total": 50},
    {"serial_id": 6, "category": 3, "total": 40},
    {"serial_id": 7, "category": 4, "total": 40},
    {"serial_id": 8, "category": 5, "total": 40},
    {"serial_id": 9, "category": 7, "total": 40},
    {"serial_id": 10, "category": 8, "total": 40}
]

cutoff_df = pd.DataFrame(cutoff_data)

### MERIT

#### CODE

In [13]:
def get_merit_by_postcode(candidate_df):    
    candidate_df['merit'] = None
    
    grouped = candidate_df.groupby('post_code')
    
    for postcode, group in grouped:
        candidates = group[
            group['total'].notnull()
        ].sort_values(
            by=['total', 'score', 'parta_gi', 'partb_ga', 'partc_qa', 'dob', 'name'], 
            ascending=[False, False, False, False, False, True, True]
        )
        
        candidates['merit'] = range(1, len(candidates) + 1)
        
        candidate_df.loc[candidates.index, 'merit'] = candidates['merit']
    
    return "{flag_name} updated successfully for {merit} candidates".format(
        flag_name='merit',
        merit=candidate_df['merit'].notnull().sum())

#### EXECUTION

In [14]:
get_merit_by_postcode(candidate_df)

'merit updated successfully for 27395 candidates'

In [15]:
candidate_df[['rollno', 'merit']].head()

       rollno merit
0  3007306679   392
1  3010303077   757
2  2003302538   656
3  9011300033  1105
4  4205300879   647

### CUTOFF FLAG

#### CODE

In [16]:
def get_cutoff(cutoff_df, candidate_df):

    cutoff = 'cutoff_flag'
    sorted_candidates = candidate_df[candidate_df['merit'].notnull()].sort_values(by='merit')

    candidate_df[cutoff] = None
    cutoff_dict = {}
    
    for index, row in cutoff_df.iterrows():
        category = int(row['category'])
        total = float(row['total'])
        cutoff_dict[category] = total
    
    
    def calculate_cutoff(candidate):
        cutoff = ''
    
        if (candidate['total'] >= cutoff_dict[9]):
            cutoff += '9'

        for cat in [0, 1, 2, 6]:
            if (candidate['cat1'] == cat) & (cat in cutoff_dict):
                if (candidate['total'] >= cutoff_dict[cat]):
                    cutoff += str(cat)

        if (candidate['cat2'] == 3) & (3 in cutoff_dict):
            if (candidate['total'] >= cutoff_dict[3]):
                cutoff += '3'

        for cat in [4, 5, 7, 8]:
            if (candidate['cat3'] == cat) & (cat in cutoff_dict):
                if (candidate['total'] >= cutoff_dict[cat]):
                    cutoff += str(cat)

        return cutoff

    sorted_candidates[cutoff] = sorted_candidates.apply(lambda row: calculate_cutoff(row), axis=1)
    candidate_df.update(sorted_candidates)

    return f"{cutoff} updated successfully"

#### EXECUTION

In [17]:
get_cutoff(cutoff_df, candidate_df)

'cutoff_flag updated successfully'

In [18]:
candidate_df[['rollno', 'level_of_post', 'cutoff_flag']].head(10)

       rollno level_of_post cutoff_flag
0  3007306679      GRADUATE           9
1  3010303077      GRADUATE          91
2  2003302538      GRADUATE          92
3  9011300033      GRADUATE           1
4  4205300879      GRADUATE           9
5  3206304268      GRADUATE         914
6  3011304642      GRADUATE          96
7  2002311681      GRADUATE          92
8  7002301245      GRADUATE           1
9  3009300841      GRADUATE

In [19]:
candidate_df['cutoff_flag'].value_counts()

cutoff_flag
96     9142
91     6689
9      3792
90     2272
92     1605
       1221
1       478
6       390
964     324
94      168
965     161
2       150
967     136
95      127
904      89
914      76
0        63
97       60
5        59
4        47
905      36
64       31
963      26
917      24
93       24
915      23
907      21
968      20
14       18
7        18
65       15
98       14
924      11
04        9
67        9
918       7
15        4
8         4
25        4
908       3
927       3
27        3
63        2
913       2
17        2
24        2
3         2
05        2
28        1
925       1
18        1
08        1
38        1
07        1
928       1
Name: count, dtype: int64

### DOB FLAG

#### PREREQIUSITES

In [20]:
mask = candidate_df['cat1'].isnull()
candidate_df.loc[mask, 'cat1'] = ''
candidate_df.loc[~mask, 'cat1'] = candidate_df.loc[~mask, 'cat1'].astype(int).astype(str)

mask = candidate_df['cat2'].isnull()
candidate_df.loc[mask, 'cat2'] = ''
candidate_df.loc[~mask, 'cat2'] = candidate_df.loc[~mask, 'cat2'].astype(int).astype(str)

mask = candidate_df['cat3'].isnull()
candidate_df.loc[mask, 'cat3'] = ''
candidate_df.loc[~mask, 'cat3'] = candidate_df.loc[~mask, 'cat3'].astype(int).astype(str)

mask = candidate_df['agerelax_code'].isnull()
candidate_df.loc[mask, 'agerelax_code'] = ''
candidate_df.loc[~mask, 'agerelax_code'] = candidate_df.loc[~mask, 'agerelax_code'].astype(int).astype(str)

In [21]:
def convert_service_period(df, column_name):
    def extract_values(text):
        if pd.isna(text):
            return None, None, None

        years, months, days = 0, 0, 0
        matches = re.findall(r'(\d+)\s*(Year[s]*)', text)
        if matches:
            years = int(matches[0][0])

        matches = re.findall(r'(\d+)\s*(Month[s]*)', text)
        if matches:
            months = int(matches[0][0])

        matches = re.findall(r'(\d+)\s*(Day[s]*)', text)
        if matches:
            days = int(matches[0][0])

        return years, months, days

    extracted_data = df[column_name].apply(extract_values)
    df[['exsm_yrs', 'exsm_months', 'exsm_days']] = pd.DataFrame(extracted_data.tolist(), index=df.index)

convert_service_period(candidate_df, 'lengthofservice')

#### CODE

In [22]:
candidate_df['agerelax_code'].unique()

array(['', '1', '2', '5', '3', '4', '8', '9', '6', '12', '10', '13', '11'],
      dtype=object)

In [23]:
def get_dob_flag(candidate_df, arc_df, post_age_df):
    
    dob_flag = 'dob_flag'
    
    candidate_df[dob_flag] = ''
    
    def calculate_verification_flag(row):
        dob_from_date = pd.to_datetime(post_age_df[post_age_df['post_code'] == row['post_code']]['dob_from'].iloc[0])
        dob_to_date = pd.to_datetime(post_age_df[post_age_df['post_code'] == row['post_code']]['dob_upto'].iloc[0])

        dob = row['dob']
        verification_flag = ''
        
        if dob >= dob_to_date:
            verification_flag = 'U'
        
        elif dob_from_date < dob < dob_to_date:
            verification_flag = '9'
        
        elif dob <= dob_from_date:
            agerelax_code = row['agerelax_code']
            
            if pd.isna(agerelax_code) or agerelax_code == '':
                agerelax_code = '99'
            
            if isinstance(agerelax_code, str):
                agerelax_code = agerelax_code.strip()
                
            if agerelax_code == '99':
                return agerelax_code
            elif agerelax_code in ['10', '11', '12', '13']:
                arc_row = arc_df[(row['age_limit'] == arc_df['age_group']) & (agerelax_code == arc_df['arc_code'].astype(str))].iloc[0]      
            else:
                arc_row = arc_df[agerelax_code == arc_df['arc_code'].astype(str)].iloc[0]
            
            age_rlx_year = int(arc_row['arc_year'])
            
            if agerelax_code == '6':
                ex_service_years = row['exsm_yrs']
                ex_service_months = row['exsm_months']
                ex_service_days = row['exsm_days']
                age_rlx_year += int(ex_service_years) if ex_service_years else 0
                
                new_dob = dob + pd.DateOffset(years=age_rlx_year, months=ex_service_months, days=ex_service_days)
            else:
                extract_year = dob.year
                extract_month = dob.month
                extract_day = dob.day
                new_year = int(extract_year) + int(age_rlx_year)
                
                if extract_month == 2 and extract_day == 29:
                    extract_day = 28
            
                new_dob = pd.to_datetime(f"{new_year}-{extract_month}-{extract_day}", format='%Y-%m-%d')
                
            if new_dob > dob_from_date:
                if len(agerelax_code) < 2:
                    verification_flag = '0' + agerelax_code
                else:
                    verification_flag = agerelax_code
            else:
                verification_flag = '99'

        return verification_flag

    sorted_candidates = candidate_df[(candidate_df['merit'].notnull())]
    
    sorted_candidates[dob_flag] = sorted_candidates.apply(calculate_verification_flag, axis=1)

    candidate_df.update(sorted_candidates)
    
    return f"{dob_flag} updated successfully"

#### EXECUTION

In [24]:
get_dob_flag(candidate_df, arc_df, post_age_df)

'dob_flag updated successfully'

In [25]:
candidate_df[['rollno', 'dob',  'agerelax_code', 'dob_flag']].head()

       rollno        dob agerelax_code dob_flag
0  3007306679 1997-07-04                      9
1  3010303077 1997-08-10             1        9
2  2003302538 1995-04-29             1       01
3  9011300033 1995-11-29             1        9
4  4205300879 2003-08-19                      9

In [79]:
def update_dob_flags(candidate_df):
    # Define base flag column name
    dob_flag_base = 'dob_flag'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{dob_flag_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in candidate_df['age_limit'].dropna().unique()}

    # Update the dob_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        # Avoid unnecessary operations by filtering first
        mask = candidate_df['age_limit'] == age_limit
        if col_name not in candidate_df.columns:
            candidate_df[col_name] = ''
        
        candidate_df.loc[mask, col_name] = candidate_df.loc[mask, dob_flag_base]
    
    return "DOB flags updated successfully"

update_dob_flags(candidate_df)

'DOB flags updated successfully'

In [26]:
candidate_df.head(30)

,regno,rollno,name,genderid,dob,cat1,cat2,cat3,lengthofservice,exs_reservation,...,partc_qa,score,total,key_new,merit,cutoff_flag,exsm_yrs,exsm_months,exsm_days,dob_flag
0,10006494972,3007306679,SAURABH KUMAR NIGAM,2,1997-07-04,9,,,NaN,NaN,...,19.5,85.5,79.60895,10006494972CR11125,392,9,NaN,NaN,NaN,9
1,10000003581,3010303077,SUMIT VERMA,2,1997-08-10,1,,,NaN,NaN,...,18.5,63.5,60.35288,10000003581CR11125,757,91,NaN,NaN,NaN,9
2,10000796373,2003302538,AMIT KUMAR,2,1995-04-29,2,,,NaN,NaN,...,21.0,66.5,65.35391,10000796373CR11125,656,92,NaN,NaN,NaN,01
3,10011615154,9011300033,SHIVARAJ KONNUR,2,1995-11-29,1,,,NaN,NaN,...,12.5,44.0,43.00586,10011615154CR11125,1105,1,NaN,NaN,NaN,9
4,10001435195,4205300879,TAMAL DAS,2,2003-08-19,9,,,NaN,NaN,...,20.5,57.5,65.92499,10001435195CR11125,647,9,NaN,NaN,NaN,9
5,10000077433,3206304268,SANDEEP KUMAR,2,1999-12-11,1,,4,NaN,NaN,...,43.0,97.0,108.01145,10000077433CR11125,88,914,NaN,NaN,NaN,9
6,10001045250,3011304642,SIDDHARTH,2,1992-08-17,6,,,NaN,NaN,...,21.0,70.5,69.54460,10001045250CR11125,579,96,NaN,NaN,NaN,02
7,10000104860,2002311681,BARUDATT NAUTIYAL,2,1995-02-02,2,,,NaN,NaN,...,12.5,83.5,77.76573,10000104860CR11125,418,92,NaN,NaN,NaN,01
8,10018914193,7002301245,DHAMMAR SAGARKUMAR PRAFULBHAI,2,2005-08-01,1,,,NaN,NaN,...,11.0,51.0,47.98199,10018914193CR11125,1027,1,NaN,NaN,NaN,9
9,10005925212,3009300841,AMIT KUMAR,2,1999-06-07,6,,,NaN,NaN,...,10.0,42.5,46.94018,10005925212CR11125,1044,,NaN,NaN,NaN,9
10,10000677111,7001300446,DHAVALKUMAR PARMAR,2,1998-08-06,1,,,NaN,NaN,...,22.5,77.0,86.61258,10000677111CR11125,291,91,NaN,NaN,NaN,9
11,10005606042,2201311259,MANISH KUMAR RAJAK,2,1998-07-20,1,,4,NaN,NaN,...,15.5,59.0,57.73006,10005606042CR11125,823,14,NaN,NaN,NaN,9
12,10012609853,3007303897,MIHIR GUPTA,2,2003-03-08,6,,,NaN,NaN,...,14.5,65.5,64.36358,10012609853CR11125,677,96,NaN,NaN,NaN,9
13,10011455674,3011305902,SOVENDRA KUMAR,2,2002-09-16,6,,,NaN,NaN,...,35.0,92.5,75.40072,10011455674CR11125,467,96,NaN,NaN,NaN,9
14,10006101494,2002310632,AKHILESH DUTTA,2,1996-10-06,9,,,NaN,NaN,...,29.0,98.0,90.28993,10006101494CR11125,245,9,NaN,NaN,NaN,9
15,10001114649,2201330289,ABHISHEK KUMAR PATHAK,2,1996-01-21,9,,,NaN,NaN,...,24.0,92.0,74.91605,10001114649CR11125,475,9,NaN,NaN,NaN,9
16,10000090663,3011309322,LOKENDRA,2,1987-08-02,9,,4,NaN,NaN,...,38.0,110.5,101.19282,10000090663CR11125,136,94,NaN,NaN,NaN,03
17,10001320013,9001304243,MASHALE SNEHAL NAGRAJ,1,1993-10-29,6,,,NaN,NaN,...,21.0,81.0,75.70160,10001320013CR11125,462,96,NaN,NaN,NaN,02
18,10011134987,3005301933,SACHIN KATARIYA,2,2004-12-27,6,,4,NaN,NaN,...,18.0,62.0,61.53311,10011134987CR11125,730,964,NaN,NaN,NaN,9
19,10001789326,3009300394,DEVANG AWASTHI,2,2004-11-02,0,,,NaN,NaN,...,25.0,75.0,87.27118,10001789326CR11125,280,90,NaN,NaN,NaN,9
20,10005728597,8201302357,SULAIMANKHAN J,2,2005-06-26,6,,,NaN,NaN,...,7.5,55.0,51.09398,10005728597CR11125,966,6,NaN,NaN,NaN,9
21,10017498888,4206300779,ANKIT VERMA,2,2002-07-07,9,,,NaN,NaN,...,4.0,44.0,39.54264,10017498888CR11125,1151,,NaN,NaN,NaN,9
22,10012111768,9206301851,ASWIN MANOJ P,2,2000-04-14,6,,4,NaN,NaN,...,21.0,88.0,88.15834,10012111768CR11125,268,964,NaN,NaN,NaN,9
23,10013362350,2201332214,PRIYA,1,2003-02-16,9,,,NaN,NaN,...,29.5,109.0,101.93050,10013362350CR11125,132,9,NaN,NaN,NaN,9
24,10001337017,2201308159,GAURAV KUMAR,2,1997-05-02,1,,,NaN,NaN,...,36.0,98.0,109.85992,10001337017CR11125,78,91,NaN,NaN,NaN,9
25,10005962557,3005302345,HARI VANSH,2,2000-07-08,1,,,NaN,NaN,...,23.0,85.0,80.42832,10005962557CR11125,378,91,NaN,NaN,NaN,9
26,10001141187,3013311859,ANKIT VISHWAKARMA,2,2005-10-20,6,,,NaN,NaN,...,18.0,40.5,38.02527,10001141187CR11125,1175,,NaN,NaN,NaN,9
27,10016363139,3007301579,VISHESH JAISWAL,2,2004-07-18,6,,,NaN,NaN,...,17.5,80.0,90.00031,10016363139CR11125,250,96,NaN,NaN,NaN,9
28,10006642542,3011305221,AMIT KUMAR,2,1995-12-25,6,,,NaN,NaN,...,19.0,66.0,64.87456,10006642542CR11125,664,96,NaN,NaN,NaN,9
29,10010211621,3013307458,SATENDRA KUMAR YADAV,2,2005-01-01,6,,,NaN,NaN,...,18.0,47.0,45.95305,10010211621CR11125,1066,,NaN,NaN,NaN,9

### CATSEL DOB FLAG

#### PREREQUISITES

In [27]:
arc_df['arc_code'] = arc_df['arc_code'].astype(str)

mask = arc_df['arc_cat2'].isnull()
arc_df.loc[mask, 'arc_cat2'] = ''

In [28]:
arc_df['arc_code'] = arc_df['arc_code'].apply(lambda x: str(x).zfill(2))

#### CODE

In [29]:
def get_catsel_dob(candidate_df, arc_df, post_age_df):
    
    dob_flag = 'dob_flag'
    catsel_dob_flag = 'catsel_dob_flag'
    
    candidate_df[catsel_dob_flag] = ''
    
    filtered_and_sorted_candidates = candidate_df[(candidate_df['merit'].notnull()) 
    & (candidate_df[dob_flag].notnull()) 
    & (candidate_df[dob_flag] != '')]
    
    def calculate_catsel_dob(row, dob_flag_name):
        dob_flag = row[dob_flag_name]
        dob_from_date = pd.to_datetime(post_age_df[post_age_df['post_code'] == row['post_code']]['dob_from'].iloc[0])
        
        if dob_flag is not None and dob_flag != '' and dob_flag != '9' and dob_flag != 'U':
            if dob_flag in ['10', '11', '12', '13']:
                catsel = arc_df[(row['age_limit'] == arc_df['age_group']) & (dob_flag == arc_df['arc_code'].astype(str))].iloc[0]
            else:
                if dob_flag != '99':
                    catsel = arc_df[arc_df['arc_code'].astype(str) == dob_flag].iloc[0]
                else:
                    return dob_flag

            if not catsel.empty:
                catsel_cat1 = catsel['arc_cat1'].split(',')
                catsel_cat2 = str(catsel['arc_cat2']).split(',')
                catsel_gender = catsel['arc_gender'].split(',')
                condition = (str(row['cat1']) in catsel_cat1) & (str(int(row['genderid'])) in catsel_gender)
                catsel_dob = ''
                if row['cat2'] == '3' and row['cat2'] in catsel_cat2:
                    catsel_dob = row['cat2']
                else:
                    if pd.isnull(catsel['arc_year_against_ur']):
                        catsel['arc_year_against_ur'] = 0
                    dob_datetime = pd.to_datetime(row['dob'])
                    extract_year = dob_datetime.year
                    extract_month = dob_datetime.month
                    extract_day = dob_datetime.day
                    if (extract_day == 29) and (extract_month == 2):
                        extract_day = 28
                    new_year = extract_year + int(catsel['arc_year_against_ur'])
                    new_dob = pd.to_datetime(f'{new_year}-{extract_month}-{extract_day}')
                    catsel_dob_decision = new_dob > dob_from_date
                    catsel_dob = '9' if catsel_dob_decision else row['cat1']
                    
                return catsel_dob if condition else ''
            else:
                return ''
        else:
            return dob_flag
    
    filtered_and_sorted_candidates[catsel_dob_flag] = filtered_and_sorted_candidates.apply(calculate_catsel_dob, args = (dob_flag, ), axis=1)
    candidate_df.update(filtered_and_sorted_candidates)
    
    print('Successfully updated ' + catsel_dob_flag)

#### EXECUTION

In [30]:
get_catsel_dob(candidate_df, arc_df, post_age_df)

Successfully updated catsel_dob_flag

In [31]:
candidate_df[['rollno', 'level_of_post', 'catsel_dob_flag']].head()

       rollno level_of_post catsel_dob_flag
0  3007306679      GRADUATE               9
1  3010303077      GRADUATE               9
2  2003302538      GRADUATE               2
3  9011300033      GRADUATE               9
4  4205300879      GRADUATE               9

In [ ]:
def update_catsel_dob_flags(candidate_df):
    # Define base flag column names
    catsel_dob_base = 'catsel_dob_flag'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{catsel_dob_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in candidate_df['age_limit'].dropna().unique()}

    # Update the catsel_dob_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        mask = candidate_df['age_limit'] == age_limit
        if col_name not in candidate_df.columns:
            candidate_df[col_name] = ''
        
        candidate_df.loc[mask, col_name] = candidate_df.loc[mask, catsel_dob_base]
    
    return "Catsel DOB flags updated successfully"

#update_catsel_dob_flags(candidate_df)

### CATSEL FLAG

In [32]:
mask = candidate_df['catsel_dob_flag'].isnull()
candidate_df.loc[mask, 'catsel_dob_flag'] = ''
candidate_df.loc[~mask, 'catsel_dob_flag'] = candidate_df.loc[~mask, 'catsel_dob_flag'].astype(str)

#### CODE

In [33]:
def get_catsel(candidate_df):

    cutoff_flag = 'cutoff_flag'
    catsel_flag = 'catsel'
    catsel_dob_flag = 'catsel_dob_flag'
    
    candidate_df[catsel_flag] = ''
    
    candidates = candidate_df[(candidate_df['merit'].notnull())].sort_values(by='rollno')
    
    def update_cutoff_flag(candidate_record):
        if candidate_record['cat2'] == '3' and candidate_record['exs_reservation'] == 'No':
            candidate_record[cutoff_flag] = candidate_record[cutoff_flag].replace('3', '').strip()

        if candidate_record[catsel_dob_flag] in ['1', '2', '6', '4', '5', '7', '8']:
            return candidate_record[cutoff_flag].replace('9', '').strip()
        elif pd.isna(candidate_record[catsel_dob_flag]) or candidate_record[catsel_dob_flag] == '':
            return ''
        else:
            return candidate_record[cutoff_flag]
    
    candidate_df[catsel_flag] = candidates.apply(update_cutoff_flag, axis=1)

    return 'Successfully updated '+ catsel_flag

#### EXECUTION

In [34]:
get_catsel(candidate_df)

'Successfully updated catsel'

In [35]:
candidate_df[['rollno', 'catsel']].head()

       rollno catsel
0  3007306679      9
1  3010303077     91
2  2003302538      2
3  9011300033      1
4  4205300879      9

In [ ]:
def update_catsel_flags(candidate_df):
    # Define base flag column name
    catsel_base = 'catsel'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{catsel_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in candidate_df['age_limit'].dropna().unique()}

    # Update the catsel_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        mask = candidate_df['age_limit'] == age_limit
        if col_name not in candidate_df.columns:
            candidate_df[col_name] = ''
        
        candidate_df.loc[mask, col_name] = candidate_df.loc[mask, catsel_base]
    
    return "Catsel flags updated successfully"

# Example usage:
# Assuming candidate_df is your DataFrame and catsel has already been calculated
#update_catsel_flags(candidate_df)

#### Updating Debarred

In [ ]:
candidate_df['debarred_flag']= False
candidate_df.loc[candidate_df['reg_no'].isin(debarred_regno), 'debarred_flag'] = True

In [ ]:
candidate_df[candidate_df['debarred_flag']==True]['rollno'].to_csv(r"C:\Users\AviralChaudhary\Documents\rhq2024\debarred_candidates.csv", index = False)

#### Updating ESMs

In [ ]:
candidate_df[((candidate_df['cat2'] == '3') & (candidate_df['post_code'].isin(group_b_posts)))]['catsel'].value_counts()

In [ ]:
candidate_df[((candidate_df['cat2'] == '3') & (candidate_df['post_code'].isin(group_b_posts)))]['catsel'] = candidate_df[((candidate_df['cat2'] == '3') & (candidate_df['post_code'].isin(group_b_posts)))]['catsel'].replace('3', '')

In [ ]:
candidate_df[((candidate_df['cat2'] == '3') & (candidate_df['post_code'].isin(group_b_posts)))]['catsel'].unique()

In [ ]:
cand['dob_flag'].unique()

## ALLOCATION

In [66]:
# cand = pd.read_csv(r"C:\Users\AviralChaudhary\Documents\rhq2024\allocated_candidates.csv")
cand = candidate_df.copy()
vac = vacancy_df.copy()

In [ ]:
mask = cand['catsel'].isnull()
cand.loc[mask, 'catsel'] = ''
cand.loc[~mask, 'catsel'] = cand.loc[~mask, 'catsel'].astype(int).astype(str)

In [67]:
cand['catsel'].unique()

array(['9', '91', '2', '1', '914', '6', '', '14', '96', '94', '964', '90',
       '95', '92', '64', '97', '0', '4', '7', '04', '93', '5', '904',
       '28', '913', '963', '24', '98', '65', '8', '915', '3', '967',
       '965', '907', '67', '917', '17', '15', '63', '905', '05', '968',
       '924', '927', '25', '925', '918', '18', '908', '08', '27', '07'],
      dtype=object)

In [6]:
# cand.loc[cand['rollno'].isin([1423006128, 5423055843, 1421010739, 7421005386, 5421027500, 5422039783, 5423040300, 7423005918, 5423109678, 7423002945, 5422111173, 5421085322, 1421049859, 7423005927, 5423000755, 5423104537, 1421008537, 1423003293, 1421012678, 4421015188, 7423008606, 7421013750, 5421056352, 7422016620, 7423003772, 1423090700, 5422076752, 1422004557, 5421028966, 1421102343, 5423065669, 1423006551, 1423003625, 1421006177, 5423068233]), 'catsel'] = ''

In [21]:
# cand[cand['rollno'].isin([1423006128, 5423055843, 1421010739, 7421005386, 5421027500, 5422039783, 5423040300, 7423005918, 5423109678, 7423002945, 5422111173, 5421085322, 1421049859, 7423005927, 5423000755, 5423104537, 1421008537, 1423003293, 1421012678, 4421015188, 7423008606, 7421013750, 5421056352, 7422016620, 7423003772, 1423090700, 5422076752, 1422004557, 5421028966, 1421102343, 5423065669, 1423006551, 1423003625, 1421006177, 5423068233])]['reg_no'].nunique()

14

In [68]:
cand[['allocated_category', 'allocated_post', 'allocated_eq']] = None

In [69]:
vac['current'] = vac['initial_vacancy']
vac['allocated'] = 0
vac['left_vacancy'] = vac['current']
vacancy_dict = {}
vac['key'] = vac['category_code'].astype(str) + vac['post_code'].astype(str)
for index, row in vac.iterrows():
    key = row['key']
    vacancy_dict[key] = row.to_dict()

#### CODE

In [70]:
def update_allocation(candidates_df, category, post, candidate, eq):
    '''if str(category) in ['3', '4', '5', '7', '8']:
    
        key_cat1 = str(category) + str(post)
        
        if (key_cat1 not in vacancy_dict.keys()) or (vacancy_dict[key_cat1]['initial'] == 0):
            keyCat2= '9' + str(post)
            
            if (keyCat2 not in vacancy_dict.keys()) or (vacancy_dict[keyCat2]['initial'] == 0):
                return False
            else:
                if vacancy_dict[keyCat2]['allocated_hc'] != vacancy_dict[keyCat2]['initial']:
                    vacancy_dict[keyCat2]['allocated_hc'] += 1
        else:
            if vacancy_dict[key_cat1]['allocated_hc'] != vacancy_dict[key_cat1]['initial']:
                vacancy_dict[key_cat1]['allocated_hc'] += 1
            
            else :
                return False'''
                        
    candidates_df.loc[candidate.name, 'allocated_category'] = category
    candidates_df.loc[candidate.name, 'allocated_post'] = post
    candidates_df.loc[candidate.name, 'allocated_eq'] = eq
    
    return True

In [71]:
def allocate_candidates(candidates_df, vacancy_dict):
     
    filtered_candidates = candidates_df[((candidates_df['merit'].notnull()) | (candidates_df['catsel'] != ''))].sort_values(by='merit')
    
    for idx, candidate in filtered_candidates.iterrows():
        allocated = False
        roll = candidate['rollno']
        DOB = candidate['dob']
        gender = str(candidate['genderid'])
        catsel = candidate['catsel']
        eq = candidate['level_of_post']
        
        for category in catsel:
            post = candidate['post_code']
            allocated_against_ur = ''
                            
            key = str(category) + str(post)
            if key in vacancy_dict and vacancy_dict[key]['current'] > 0 and gender in vacancy_dict[key]['gender'].split(','):
                allocated = update_allocation(candidates_df, category, post, candidate, eq)
                if allocated:
                    vacancy_dict[key]['current'] -= 1
                    vacancy_dict[key]['allocated'] += 1
                    break

    return vacancy_dict

In [13]:
# def adjust_vacancy(candidates_df, vacancy_df):
#     vacancy_df['current'] = vacancy_df['initial_vacancy'] - vacancy_df['allocated_hc']
#     vacancy_df['allocated'] = 0
#     vacancy_df['left_vacancy'] = 0
        
#     vacancy_df['allocated_hc_prev'] = vacancy_df['allocated_hc']
#     vacancy_df['allocated_hc'] = 0

#     return vacancy_df

#### EXECUTION

##### FIRST TIME

In [72]:
upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)
updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')

In [73]:
cand[cand['allocated_category'].notnull()].shape[0]

1411

In [ ]:
cand = cand.sort_values(by = ['reg_no', 'rollno'])

In [46]:
updated_vacancy_df['left_vacancy'].sum()

np.int64(14406)

##### ADJUST LOOP

In [ ]:
'''
i=0
while (updated_vacancy_df['allocated_hc_prev'] != updated_vacancy_df['allocated_hc']).any():
    i+=1
    print('Adjust Attempt-'+str(i))
    upd_vacancy_df = adjust_vacancy(cand, updated_vacancy_df)
    
    upd_vacancy_df['left_vacancy'] = upd_vacancy_df['current']
    vacancy_dict = {}
    upd_vacancy_df['key'] = upd_vacancy_df['state_code'].astype(str) + upd_vacancy_df['gender'].astype(str) + upd_vacancy_df['post_code'].astype(str) + upd_vacancy_df['area'].astype(str) + upd_vacancy_df['category_code'].astype(str)
    
    for index, row in upd_vacancy_df.iterrows():
        key = row['key']
        vacancy_dict[key] = row.to_dict()
    cand[['allocated_category', 'allocated_post', 'allocated_against_ur', 'allocated_medium']] = None
    upd_vacancy_dict = allocate_candidates(cand, vacancy_dict)
    updated_vacancy_df = pd.DataFrame.from_dict(upd_vacancy_dict, orient='index')'''

In [74]:
updated_vacancy_df[['min_marks', 'min_marks_parta', 'min_marks_partb', 'min_marks_partc', 'min_marks_cand_dob', 'min_marks_merit']] = None

In [48]:
# def find_lowest_marks(candidates_df, vacancy_df):

#     # allocated_candidates = candidates_df[candidates_df['allocated_category'].notnull()].copy()
#     # allocated_candidates['key'] = (allocated_candidates['allocated_category'].astype(int).astype(str) +
#     #                         allocated_candidates['allocated_post'].astype(str))

#     candidates_df['key'] = (candidates_df['allocated_category'].astype(str) +
#                            candidates_df['allocated_post'].astype(str))
                            
#     vacancy_df['key'] = (vacancy_df['category_code'].astype(str)+
#                         vacancy_df['post_code'].astype(str))
                         
#     highest_merit_candidates = candidates_df.loc[candidates_df.groupby('key')['merit'].idxmax()]
    

#     upd_vacancy_df = vacancy_df.merge(highest_merit_candidates[['key', 'total', 'parta_gi', 'partb_ga', 'partc_qa', 'dob']],
#                                   on='key', how='left')

#     vacancy_df['min_marks'] = upd_vacancy_df['total']
#     vacancy_df['min_marks_parta'] = upd_vacancy_df['parta_gi']
#     vacancy_df['min_marks_partb'] = upd_vacancy_df['partb_ga']
#     vacancy_df['min_marks_partc'] = upd_vacancy_df['partc_qa']
#     vacancy_df['min_marks_cand_dob'] = upd_vacancy_df['dob']

#     del(upd_vacancy_df)

#     return vacancy_df

In [75]:
# from CTGD
def find_lowest_marks(candidates_df, vacancy_df):
    candidates_df['key'] = (candidates_df['allocated_post'].astype(str) +
                            candidates_df['allocated_category'].astype(str))

    vacancy_df['key'] = (vacancy_df['post_code'].astype(str) +
                         vacancy_df['category_code'].astype(str))

    highest_merit_candidates = candidates_df.loc[candidates_df.groupby('key')['merit'].idxmax()]

    vacancy_df_merged = vacancy_df.merge(highest_merit_candidates[['key', 'total', 'parta_gi', 'partb_ga', 'partc_qa', 'dob']],
                                  on='key', how='left')

    vacancy_df_merged['min_marks'] = vacancy_df_merged['total']
    vacancy_df_merged['min_marks_parta'] = vacancy_df_merged['parta_gi']
    vacancy_df_merged['min_marks_partb'] = vacancy_df_merged['partb_ga']
    vacancy_df_merged['min_marks_partc'] = vacancy_df_merged['partc_qa']
    vacancy_df_merged['min_marks_cand_dob'] = vacancy_df_merged['dob']
    # vacancy_df_merged['min_marks_merit'] = vacancy_df_merged['merit']

    return vacancy_df_merged

In [76]:
updated_vacancy_df = find_lowest_marks(cand, updated_vacancy_df)

In [77]:
cand['allocated_category'].unique()

array([None, '4', '9', '7', '0', '5', '6', '8'], dtype=object)

In [ ]:
highest_merit_candidates

In [53]:
updated_vacancy_df.head()

,region,post_code,post_name,department,age,pay_scale,eq_level,gender,category,category_code,...,min_marks_parta,min_marks_partb,min_marks_partc,min_marks_cand_dob,min_marks_merit,total,parta_gi,partb_ga,partc_qa,dob
0,CR,CR11125,MANAGER-CUM-ACCOUNTANT,"NATIONAL SUGAR INSTITUTE, DEPARTMENT OF FOOD A...",18-30,Level 6,Graduation & Above,"1,2,3",ST,2,...,NaN,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,NaT
1,CR,CR11125,MANAGER-CUM-ACCOUNTANT,"NATIONAL SUGAR INSTITUTE, DEPARTMENT OF FOOD A...",18-30,Level 6,Graduation & Above,"1,2,3",UR,9,...,35.0,7.5,35.5,2001-10-23,None,120.67804,35.0,7.5,35.5,2001-10-23
2,CR,CR11125,MANAGER-CUM-ACCOUNTANT,"NATIONAL SUGAR INSTITUTE, DEPARTMENT OF FOOD A...",18-30,Level 6,Graduation & Above,"1,2,3",HH,5,...,NaN,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,NaT
3,CR,CR11125,MANAGER-CUM-ACCOUNTANT,"NATIONAL SUGAR INSTITUTE, DEPARTMENT OF FOOD A...",18-30,Level 6,Graduation & Above,"1,2,3",VH,7,...,NaN,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,NaT
4,CR,CR11125,MANAGER-CUM-ACCOUNTANT,"NATIONAL SUGAR INSTITUTE, DEPARTMENT OF FOOD A...",18-30,Level 6,Graduation & Above,"1,2,3",OBC,6,...,NaN,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,NaT

In [78]:
updated_vacancy_df['left_vacancy'] = updated_vacancy_df['current']
updated_vacancy_df['current'] = updated_vacancy_df['left_vacancy'] + updated_vacancy_df['allocated']

In [ ]:
cand.columns

In [ ]:
cand = cand.sort_values(by = ['reg_no', 'post_code', 'rollno'])

In [ ]:
cand[['total', 'cutoff_flag', 'dob', 'age_limit', 'agerelax_code', 'dob_flag', 'catsel', 'post_code' ]].head(20)

In [ ]:
post_age_df[post_age_df['post_code'] == 'WR15824']

#### WRITING TO CSV

In [84]:
cand.columns

Index(['regno', 'rollno', 'name', 'genderid', 'dob', 'cat1', 'cat2', 'cat3',
       'lengthofservice', 'exs_reservation', 'agerelax_code', 'post_code',
       'level_of_post', 'age_limit', 'parta_gi', 'partb_ga', 'partc_qa',
       'score', 'total', 'key_new', 'merit', 'cutoff_flag', 'exsm_yrs',
       'exsm_months', 'exsm_days', 'dob_flag', 'catsel_dob_flag', 'catsel',
       'allocated_category', 'allocated_post', 'allocated_eq', 'key',
       'dob_flag_18_30', 'dob_flag_18_27', 'dob_flag_18_25',
       'catsel_dob_flag_18_30', 'catsel_dob_flag_18_27',
       'catsel_dob_flag_18_25', 'catsel_18_30', 'catsel_18_27',
       'catsel_18_25'],
      dtype='object')

In [80]:
def update_dob_flags(cand):
    # Define base flag column name
    dob_flag_base = 'dob_flag'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{dob_flag_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in cand['age_limit'].dropna().unique()}

    # Update the dob_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        # Avoid unnecessary operations by filtering first
        mask = cand['age_limit'] == age_limit
        if col_name not in cand.columns:
            cand[col_name] = ''
        
        cand.loc[mask, col_name] = cand.loc[mask, dob_flag_base]
    
    return "DOB flags updated successfully"

update_dob_flags(cand)

'DOB flags updated successfully'

In [81]:
def update_catsel_dob_flags(cand):
    # Define base flag column names
    catsel_dob_base = 'catsel_dob_flag'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{catsel_dob_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in cand['age_limit'].dropna().unique()}

    # Update the catsel_dob_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        mask = cand['age_limit'] == age_limit
        if col_name not in cand.columns:
            cand[col_name] = ''
        
        cand.loc[mask, col_name] = cand.loc[mask, catsel_dob_base]
    
    return "Catsel DOB flags updated successfully"

update_catsel_dob_flags(cand)

'Catsel DOB flags updated successfully'

In [83]:
def update_catsel_flags(cand):
    # Define base flag column name
    catsel_base = 'catsel'

    # Create column names based on unique age limits
    age_limit_cols = {age_limit: f"{catsel_base}_{age_limit.replace('-', '_')}" 
                      for age_limit in cand['age_limit'].dropna().unique()}

    # Update the catsel_flag columns based on the age_limit
    for age_limit, col_name in age_limit_cols.items():
        mask = cand['age_limit'] == age_limit
        if col_name not in cand.columns:
            cand[col_name] = ''
        
        cand.loc[mask, col_name] = cand.loc[mask, catsel_base]
    
    return "Catsel flags updated successfully"

# Example usage:
# Assuming candidate_df is your DataFrame and catsel has already been calculated
update_catsel_flags(cand)

'Catsel flags updated successfully'

In [86]:
cand.to_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\27935_candidates_allocated.csv", index = False)
#cand[cand['allocated_category'].notnull()].to_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\only_allocated_candidates.csv", index = False)
#updated_vacancy_df.to_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\13_allocated_vacancy_new.csv", index = False)

In [110]:
#cand.to_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\candidates_all_columns.csv", index = False)
updated_vacancy_df.to_csv(r"C:\Users\SalauddinKhan\Desktop\RHQ 2025\RESULT\allocated_vacancy_with_min_marks.csv", index = False)